name: Atualizar Artigos

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Verificar arquivos
        run: |
          pwd
          ls -la

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Executar fetcher
        run: python fetch_articles.py

      - name: Copiar json para docs
        run: |
          mkdir -p docs
          cp data/artigos_ceara.json docs/artigos_ceara.json

      - name: Commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          git add docs/artigos_ceara.json

          git diff --cached --quiet && exit 0

          git commit -m "Atualiza artigos"
          git push
